# version: 1.0.0

FROM ubuntu:latest

RUN usermod -l user -d /home/user -m ubuntu && groupmod -n user ubuntu

RUN apt update && apt install -yq --no-install-recommends libreoffice

RUN fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

USER user
