FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user \
    && apt update

RUN DEBIAN_FRONTEND="noninteractive" TZ="Europe/London" apt install -yq --no-install-recommends \
        tzdata \
        keyboard-configuration \
        software-properties-common \
        gpg-agent \
        qt5dxcb-plugin \
        qtwayland5 \ 
    && add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable \
    && apt update \
    && apt install -yq --no-install-recommends qbittorrent \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

USER user

WORKDIR /home/user

ENTRYPOINT [ "qbittorrent" ]

# qtwayland5 package for wayland support
