#!/bin/bash

BUILDER=podman

x=("brave" "gtkcord4" "librewolf" "mullvad-browser" "obs" "qbittorrent" "staruml" "telegram" "tor" "ungoogled-chromium" "winbox" "zoom")

if [ "$1" = "selected" ] ; then
    for f in ${x[@]} ; do
        echo ">>>>>> Building $f <<<<<<"
        ${BUILDER} build -t peterzam/box-$f --no-cache -f https://codeberg.org/peterzam/box/raw/branch/main/$f/Containerfile .
    done
else
    ${BUILDER} build -t peterzam/box-$1 -f ./$1/Containerfile .
fi
