FROM python:alpine

RUN pip3 install tidal-dl --upgrade

RUN addgroup -g 1000 -S user && adduser -u 1000 -s /bin/sh -S -h /home/user -G user user

USER user

WORKDIR /home/user

ENTRYPOINT ["tidal-dl"]
