services:
  box-gtkcord4:
    image: localhost/peterzam/box-gtkcord4:latest
    container_name: "box-gtkcord4"
    userns_mode: "keep-id:uid=${PUID},gid=${PGID}"
    group_add:
      - video
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - XDG_CURRENT_DESKTOP
      - XDG_RUNTIME_DIR
      - WAYLAND_DISPLAY
    volumes:
      - /run/user/${PUID}/wayland-1:/run/user/1000/wayland-1
      - ${BOX_MOUNT}/shared/gtkcord4:/home/user/Shared
      - /usr/share/fonts:/usr/share/fonts:ro
      - ${BOX_MOUNT}/configs/gtkcord4:/home/user/.config/gtkcord4
    command: gtkcord4
