FROM alpine:latest as downloader
RUN apk add curl
RUN curl -J -L -O https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb


FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user

COPY --from=downloader --chown=user:user /dbeaver-ce* /dbeaver.deb

RUN apt update && apt install -yq --no-install-recommends \
        libswt-gtk-4-jni \
        libpulse0 \
    && dpkg -i /dbeaver.deb && rm /dbeaver.deb \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \; \
    && echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

USER user

WORKDIR /home/user

ENTRYPOINT [ "dbeaver" ]
