FROM alpine:latest as downloader
RUN apk add curl
RUN curl -J -L -O https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb


FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G video -g 1000 -m user

COPY --from=downloader --chown=user:user /dbeaver-ce* /dbeaver.deb

RUN apt update && apt install -yq --no-install-recommends \
        libswt-gtk-4-jni \
    && dpkg -i /dbeaver.deb && rm /dbeaver.deb \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

USER user

WORKDIR /home/user

ENTRYPOINT [ "dbeaver" ]
