services:
  box-ungoogled-chromium:
    image: localhost/peterzam/box-ungoogled-chromium:latest
    container_name: "box-ungoogled-chromium"
    userns_mode: "keep-id:uid=${PUID},gid=${PGID}"
    group_add:
      - video
    cap_add:
      - SYS_CHROOT
      - SYS_ADMIN
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - XDG_CURRENT_DESKTOP
      - XDG_RUNTIME_DIR
      - WAYLAND_DISPLAY
    volumes:
      - /run/user/${PUID}/wayland-1:/run/user/1000/wayland-1
      - ${BOX_MOUNT}/shared/ungoogled-chromium:/home/user/Shared
      - /run/user/${PUID}/pulse:/run/user/1000/pulse
      - /usr/share/fonts:/usr/share/fonts:ro
      - ${BOX_MOUNT}/configs/ungoogled-chromium:/home/user/.config/chromium
    shm_size: "2gb"
    command: /home/user/ungoogled-chromium/chrome --enable-features=UseOzonePlatform
      --ozone-platform=wayland --disable-top-sites
