FROM alpine:latest as downloader
RUN apk add curl
RUN curl -fSLO "https://downloads.getmonero.org/gui/linux64" && tar xvf linux64 


FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user \
    && apt update

RUN DEBIAN_FRONTEND="noninteractive" TZ="Europe/London" apt install -yq --no-install-recommends \
        keyboard-configuration \
        qt5dxcb-plugin \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

COPY --from=downloader --chown=user:user monero-gui-v* /home/user/monero

USER user

WORKDIR /home/user

ENTRYPOINT [ "/home/user/monero/monero-wallet-gui" ]
