FROM alpine:latest as downloader
RUN apk update && apk add curl
RUN curl -JLO $(curl -s https://api.github.com/repos/PolyMC/PolyMC/releases/latest | grep -E ".*url.*PolyMC-Linux-Portable-*" | cut -d '"' -f4 ) \
    && mkdir PolyMC && tar xvf PolyMC-Linux-Portable* -C PolyMC


FROM docker.io/library/openjdk:8-slim

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user \
    && apt update

RUN apt install -yq --no-install-recommends libpulse0 \
    && echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

RUN apt install -yq --no-install-recommends \
        libqt5core5a \
        libqt5network5 \
        libqt5gui5 \
        libqt5xml5 \
        libqt5widgets5 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libatspi2.0-0 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libdrm2 \
        libexpat1 \
        libgbm1 \
        libfontconfig1 \
        libgdk-pixbuf2.0-0 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango1.0-0 \
        libpangocairo-1.0-0 \
        libx11-6 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        libx11-xcb1 \
        libxcb-dri3-0 \
        libxcb1 \
        x11-xserver-utils \
        wget \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

COPY --from=downloader --chown=user:user --chmod=0700 /PolyMC/bin/polymc /usr/bin

USER user

WORKDIR /home/user

ENTRYPOINT [ "polymc" ]
