# version: 1.0.0

FROM ubuntu:latest

RUN usermod -l user -d /home/user -m ubuntu && groupmod -n user ubuntu

RUN apt-get update && apt-get install extrepo -y && extrepo enable librewolf && extrepo update librewolf

RUN apt-get update && apt-get install -yq --no-install-recommends \
    libpulse0 \
    librewolf

RUN fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoclean && apt-get autoremove --purge && apt-get clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

RUN echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

USER user
