FROM alpine:latest as downloader
RUN apk add curl
RUN curl -JL https://mt.lv/winbox64 -o winbox.exe


FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user

RUN apt update && apt install -yq --no-install-recommends \
        wine \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

COPY --from=downloader --chown=user:user /winbox.exe /home/user/

USER user

WORKDIR /home/user

ENTRYPOINT [ "/usr/bin/wine","/home/user/winbox.exe" ]
