FROM alpine:latest as downloader
RUN apk add curl
RUN curl -fsSLO https://zoom.us/client/latest/zoom_amd64.deb

FROM ubuntu:latest

RUN usermod -l user -d /home/user -m ubuntu && groupmod -n user ubuntu

COPY --from=downloader --chown=user:user /zoom_amd64.deb /zoom_amd64.deb

RUN apt update && apt install -yq --no-install-recommends \
        libnss3 \
        libasound2 \
        libpulse0 \
        qt5dxcb-plugin \
        /zoom_amd64.deb

RUN fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

RUN echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

USER user
