# version: 1.0.0

FROM alpine:latest as downloader
RUN apk add curl
RUN curl -fSL "https://discord.com/api/download?platform=linux&format=tar.gz" -o discord.tar.gz \
    && tar xzvf discord.tar.gz

FROM ubuntu:latest

RUN usermod -l user -d /home/user -m ubuntu && groupmod -n user ubuntu

RUN apt update && apt install -yq --no-install-recommends \
        keyboard-configuration \
        libgbm1 \
        libxshmfence1 \
        libdrm2 \
        libc++1 \
        gvfs \
        libcap2 \
        libgtk-3-0 \
        libcanberra-gtk3-module \
        libnotify4 \
        libnss3 \
        libxkbfile1 \
        libxss1 \
        libxtst6 \
        libx11-xcb1 \
        xdg-utils \
        libatomic1 \
        wget \
        ca-certificates \
        libpulse0

RUN fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

RUN echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

COPY --from=downloader --chown=user:user Discord /home/user/Discord

USER user
