FROM alpine:latest as downloader
RUN apk add curl
RUN curl -fSL "https://discord.com/api/download?platform=linux&format=tar.gz" -o discord.tar.gz \
    && tar xzvf discord.tar.gz


FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user \
    && apt update

RUN apt install -yq --no-install-recommends libpulse0 \
    && echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

RUN DEBIAN_FRONTEND="noninteractive" TZ="Europe/London" apt install -yq --no-install-recommends \
        tzdata \
        keyboard-configuration \
        libgbm1 \
        libxshmfence1 \
        libdrm2 \
        libc++1 \
        libappindicator1 \
        gvfs \
        libcap2 \
        libgconf-2-4 \
        libgtk-3-0 \
        libcanberra-gtk3-module \
        libnotify4 \
        libnss3 \
        libxkbfile1 \
        libxss1 \
        libxtst6 \
        libx11-xcb1 \
        xdg-utils \
        libatomic1 \
        wget \
        ca-certificates \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

COPY --from=downloader --chown=user:user Discord /home/user/Discord

USER user

WORKDIR /home/user

ENTRYPOINT [ "/home/user/Discord/Discord" ]
