services:
  box-brave-browser:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/box-brave-browser:latest
    container_name: "box-brave-browser-${RANDOM}"
    userns_mode: "keep-id:uid=${PUID},gid=${PGID}"
    cap_add:
      - SYS_CHROOT
      - SYS_ADMIN
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - XDG_CURRENT_DESKTOP
      - XDG_RUNTIME_DIR
      - WAYLAND_DISPLAY
    volumes:
      - /run/user/${PUID}/wayland-1:/run/user/1000/wayland-1
      - ${BOX_MOUNT}/shared/brave:/home/user/Shared
      - /run/user/${PUID}/pulse:/run/user/1000/pulse
      - /usr/share/fonts:/usr/share/fonts:ro
      - ${BOX_MOUNT}/configs/brave:/home/user/.config/BraveSoftware
    shm_size: "2gb"
    command:
      - --enable-features=UseOzonePlatform
      - --ozone-platform=wayland
