# version: 1.0.0

FROM ubuntu:latest

RUN usermod -l user -d /home/user -m ubuntu && groupmod -n user ubuntu

RUN apt update && apt install -yq --no-install-recommends \
        ca-certificates \
        gnupg \
        libgl1 \
        libpulse0 \
        curl \
        libegl1

RUN curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg \
    && curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser.sources \
    && apt update && apt install -yq --no-install-recommends brave-browser

RUN fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

RUN echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

USER user

WORKDIR /home/user

ENTRYPOINT [ "brave-browser" ]
