FROM alpine:latest as downloader
RUN apk add curl
RUN curl -JLO https://mullvad.net/en/download/browser/linux64/latest \
    && tar xvf latest


FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user

COPY --from=downloader --chown=user:user /mullvad-browser /home/user/mullvad-browser

RUN apt update && apt install -yq --no-install-recommends \
        keyboard-configuration \
        libgtk-3-0 \
        libxtst6 \
        libdbus-glib-1-2 \
        libasound2 \
        libavcodec58 \
        libgl1 \
        libpulse0 \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \; \
    && echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

USER user

WORKDIR /home/user/mullvad-browser

ENTRYPOINT [ "/home/user/mullvad-browser/start-mullvad-browser.desktop"]
