services:
  box-firefox:
    image: localhost/peterzam/box-firefox:latest
    container_name: "box-firefox"
    userns_mode: "keep-id:uid=${PUID},gid=${PGID}"
    group_add:
      - video
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - XDG_CURRENT_DESKTOP
      - XDG_RUNTIME_DIR
      - WAYLAND_DISPLAY
      - MOZ_ENABLE_WAYLAND=1
    volumes:
      - /run/user/${PUID}/wayland-1:/run/user/1000/wayland-1
      - ${BOX_MOUNT}/shared/firefox:/home/user/Shared
      - /run/user/${PUID}/pulse:/run/user/1000/pulse
    command: /home/user/firefox/firefox
