FROM alpine:latest as downloader
RUN apk add curl
RUN curl -JLO $(curl -s https://api.github.com/repos/obsidianmd/obsidian-releases/releases | grep -E ".*url.*amd64.deb" | cut -d '"' -f4 | head -1)

FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G video -g 1000 -m user

COPY --from=downloader --chown=user:user /obsidian* /obsidian.deb

RUN apt update && apt install -yq --no-install-recommends\
        libdrm2 \
        libgbm1 \
        libasound2 \
        libgtk-3-0 \
        libnotify4 \
        libnss3 \
        libxss1 \
        libxtst6 \
        xdg-utils \
        libatspi2.0-0 \
        libsecret-1-0 \
        ffmpeg \
        /obsidian.deb \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge && apt clean \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \; \
    && rm -rf /obsidian.deb

USER user

WORKDIR /home/user

ENTRYPOINT [ "obsidian" ]
