FROM alpine:latest as downloader
RUN apk add curl
RUN curl -J -L -O https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb


FROM ubuntu:latest

RUN groupadd -g 1000 -r user \
    && useradd -u 1000 -s /bin/bash -r -G audio,video -g 1000 -m user \
    && apt update

RUN apt install -yq --no-install-recommends libpulse0 \
    && echo "default-server = unix:/run/user/1000/pulse/native\nautospawn = no\ndaemon-binary = /bin/true\nenable-shm = false" > /etc/pulse/client.conf

COPY --from=downloader --chown=user:user /viber.deb /viber.deb

RUN apt install -yq  --no-install-recommends \
        libpulse0 \
        libasound2 \
        libnss3 \
        libgstreamer-plugins-base1.0-0 \
        libgstreamer1.0-0 \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-pulseaudio \
        gstreamer1.0-libav \
        libxcb-xinput0 \
        libxss1 \
        libgl1 \
        libegl1 \
        gstreamer1.0-gl \
        libxrandr2 \
        libxtst6 \
        libwebpdemux2 \
        libxkbcommon0 \
        libxslt1.1 \
        liblcms2-2 \
        libxkbfile1 \
        libopengl0 \
        qt5dxcb-plugin \
        ca-certificates \
    && dpkg -i /viber.deb && rm /viber.deb \
    && fc-cache -fv \
    && rm -rf /var/lib/apt/lists/* \
    && apt autoclean && apt autoremove --purge \
    && find / -xdev -type f -perm /u+s -exec chmod -c u-s {} \; \
    && find / -xdev -type f -perm /g+s -exec chmod -c g-s {} \;

USER user

WORKDIR /home/user

ENTRYPOINT [ "/opt/viber/Viber" ]
